title: James Hunt's site
description: James Hunt's site
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "default"

navbar-links:
    Author's home: "http://ifdeflinux.blogspot.com"

social-network-links:
    email: jamesodhunt@gmail.com
    github: jamesodhunt
    instagram: jamesodhunt
    twitter: jamesodhunt

encoding: UTF-8
breadcrumbs: true
