title: James Hunt's site
description: James Hunt's site
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin: "default"

encoding: UTF-8
breadcrumbs: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "sidebar"

author:
  name: James Hunt
  links:
    - label: "instagram"
      icon: "instagram"
      url: "https://instagram.com/jamesodhunt"
    - label: "twitter"
      icon: "twitter"
      url: "https://twitter.com/jamesodhunt"

#sidebar:
#  - ti#tle: "James Hunt's site"

#navbar-links:
#    Author's home: "http://ifdeflinux.blogspot.com"

#social-network-links:
#    email: jamesodhunt@gmail.com
#    github: jamesodhunt
#    instagram: jamesodhunt
#    twitter: jamesodhunt

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
