title: James Hunt's site
description: James Hunt's site
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

navbar-links:
    Author's home: "http://ifdeflinux.blogspot.com"

social-network-links:
    email: jamesodhunt@gmail.com
    github: jamesodhunt
    instagram: jamesodhunt
    twitter: jamesodhunt

encoding: UTF-8
breadcrumbs: true
